@startuml
'https://plantuml.com/sequence-diagram

class ListItem {
    +title
    +date
    +description
}

class TodoListApplication {
    -start()
}

class DataManager {
    +ItemList
    +CurrentCell


    -addItem(String title, String date, String description)
    -removeItem()
    -editCurrentCell(String date, String description)
    -sortComplete()
    -sortIncomplete()
    -showAll()
    -save(File file)
    -load(File file)
}

class TodoListController {
    +DateBox
    +DescriptionBox
    +AddBtn
    +SaveBtn
    +LoadBtn
    +ShowAllBtn
    +SortCompleteBtn
    +SortIncompleteBtn
    +RemoveBtn
    +MarkCompleteBtn
    +MarkIncompleteBtn
    +EditBtn
    +ClearListBtn

    +ListViewID

    -addItem()
    -editItem()
    -MarkCompleteBtnClick()
    -MarkIncompleteBtnClick()
    -CompleteSortBtnClick()
    -IncompleteSortBtnClick()
    -ShowAllBtnClick()
    -RemoveBtnClick()
    -RefreshList()
    -RefreshList(OberservableList<ListItem> filteredList)
    -LoadBtnClick()
    -SaveBtnClick()
    -ClearListBtnClick()

}
@enduml